### ISSUE TITLE
Главная секция

### ISSUE THREAD

**Issue by igosheva** [zariuz/burgers#7]
first-header__hamburger-link - достилизовать гамбургер-меню

**Comment by igosheva** [comment]
first-main__img-backgraund - при разрешении 768 добавляется свойство height: 100%;, убери его, оно деформирует картинку если она не влазиет по ширине

**Comment by igosheva** [comment]
wrapper - добавь min-width: 300px;

**Comment by zariuz** [comment]
Сделано
